Repository mautic/developer-documentation-new, pull requests merged in 2024-10, with the labels that each got.

#221 Create symfony_docs_event_subscribers.py
  docs/links/symfony_docs_event_subscribers.py
Labels: hacktoberfest-accepted

#222 Add select parameter in GET /contacts
  docs/rest_api/contacts.rst
Labels: bug, documentation, pending-feedback

#228 Create holopin.yml
  .github/holopin.yml
Labels: hacktoberfest-2024
